### PR TITLE
Updated number formats used in characteristics and fixed compatibility with newer HS110 revisions

### PR DESCRIPTION
**Pull request by lint2015**
Updated all characteristic number formats to reflect updated formats found here: https://gist.github.com/simont77/3f4d4330fa55b83f8ca96388d9004e7d#elgato-eve-energy-firmware-revision-131466

Added compatibility with newer HS110 hardware and software revisions that return energy metrics in much smaller units. The threshold-based inUse state requires the corresponding fix in tplink-smarthome-api to function correctly.

### CODE REVIEW

**Comment by plasticrake** [comment]
Taking a look at this today

**Comment by plasticrake** [comment]
@lint2015 Thanks for the contribution! 😄

**Comment by Itaybre** [comment]
Using the code from master, homebridge is crashing for me
I will try to get some logs and see why that is happening

**Comment by lint2015** [comment]
@Itaybre Did you manage to figured out the problem? Please post the debug log if not.

**Pull request merged**
