### PR TITLE
fix(Plug): correctly handle switches

### LINKED ISSUE #322: Duplicate Switch Devices in v8
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have HS200s and HS220s, all of which have worked perfectly for a couple of years now, until upgrading to v8 today.  Now, Homebridge and HomeKit see duplicate devices for every switch.  For each switch, I see a "switch" and an "outlet" in both Homebridge and HomeKit, both with the same name, but none of the switches work.  They only function if you toggle the "outlet" instance.  This has broken many automations since they referenced the actual switch.

### What, if anything, has recently changed?

v8

### Version

8

### Node Version

v18.15.0

### Homebridge Version

1.7.0

### Which OS/Platform?

Other (Please describe)

### Relevant log output

```shell
Running native package on Synology NAS
```

### Configuration

```json
"name": "TplinkSmarthome",
            "addCustomCharacteristics": false,
            "deviceTypes": [
                "plug",
                "bulb"
            ],
            "platform": "TplinkSmarthome"
```

### PR DESCRIPTION
**Pull request by andrewjbates**
Fixes #322

### CODE REVIEW

**Comment by plasticrake** [comment]
Thank you! I'll take your word for it that this fixes it as I don't have these devices to test.

**Comment by TinyMito** [comment]
I can confirm this is fixed in 8.0.2 - I do not see any duplicated switches anymore. Thank you very much!

**Comment by ChrisJohns-me** [comment]
Also confirming that switches are not duplicate anymore. Trying to see any other unintended side-effects, but after a quick glance, I do not see any. 👍

**Comment by andrewjbates** [comment]
I've been using this since an hour or two before I submitted the PR and haven't found any side effects. The entire plugin also seems more stable on 8.x, thanks for your hard work!

**Pull request merged**
